function defaultplot
set(gca, ...
    'Color'         ,'w'              , ...
    'Box'           , 'off'           , ...
    'TickDir'       , 'out'           , ...
    'TickLength'    , [.02 .02]       , ...
    'XColor'        , zeros(1,3)      , ...
    'YColor'        , zeros(1,3)      , ...
    'FontName'      , 'Helvetica'     , ...
    'LineWidth'     , 1               );
set(gcf, ...
    'color'         ,'w'                 );